### ISSUE TITLE
fetching file from current working branch (of PR)?

### ISSUE THREAD

**Issue by youknowone** [Bhacaz/checkout-files#17]
When I used this action for PR, I expected to getting files from *current* branch, not from the master branch of the repository.
It tried to get files from `https://api.github.com/repos/.../content/...` but failed because there was no such file.

is this intended behavior?

**Comment by Bhacaz** [comment]
Hi, yes this is intended. My thought about this is that this action is so generic that it may not be triggered by a push or a pull_request event. Other kind of trigger may not include the _current_ branch info. 

If you when specified a branch base on the context

```yml
- name: Checkout files
  uses: Bhacaz/checkout-files@v2
  with:
   files: package.json
   branch: ${{ github.head_ref || github.ref_name }} 
```

Ref: https://stackoverflow.com/a/71158878/3123484

I'll update the README to clarify this behaviour, thanks.
