### ISSUE TITLE
Checkout specific folder works only for Default branch

### ISSUE THREAD

**Issue by VeerendraSheelvantTR** [Bhacaz/checkout-files#19]
checkout specific folder from different branch from a same repo does not work. In below code main is my default branch. But i am running the workflow on poc-5.7.7-vee branch and it fails when i try to checkout automationtests folder.

      - name: Checkout files
        uses: Bhacaz/checkout-files@v2
        with:
          files: automationtests
          branch: poc-5.7.7-vee

**Comment by leon1995** [comment]
With my configuration
```yml
- name: Check out test directory
  uses: Bhacaz/checkout-files@v2
  with:
    files: tests
    branch: ${{ github.head_ref || github.ref_name }}
```
I get similar error as in #11
