### ISSUE TITLE
Does checked out files preserve file permissions?

### ISSUE THREAD

**Issue by mhung-lingraphica** [Bhacaz/checkout-files#21]
I am trying to use this to check out a subdirectory of my project instead of the whole thing, but I run into Error code 126:
```
/home/runner/work/_temp/2ddc6165-7186-415a-8d87-bc4d746f659f.sh: line 1: CICD/CreateBuildTarget.sh: Permission denied
60
Error: Process completed with exit code 126.
```
I had this working before, and made sure the files had the correct permissions:
```
myUserName@myUserNames-MacBook-Pro cicd % ls -l
total 16
-rwxr-xr-x@ 1 myUserName  staff  2239 Feb  3 11:17 CreateBuildTarget.sh
-rwxr-xr-x@ 1 myUserName  staff   449 Feb  3 11:18 DeleteBuildTarget.sh
```

I only made the below replacement:
Before (working):
```
      - name: Checkout to access bash script
        uses: actions/checkout@v2.6.0
```
After (not working):
```
      - name: Checkout to access bash script
        uses: Bhacaz/checkout-files@v2
        with:
          files: CICD
```

Am I using this wrong and should be checking out a single file, or is something else going on?
